# Label definitions — synced by .github/workflows/label-sync.yml
# Colors are hex without the #

# Priority
- name: "priority/critical"
  color: "b60205"
  description: "Must be fixed ASAP"
- name: "priority/high"
  color: "d93f0b"
  description: "Important, fix soon"
- name: "priority/medium"
  color: "fbca04"
  description: "Fix when possible"
- name: "priority/low"
  color: "0e8a16"
  description: "Nice to have"

# Type
- name: "type/bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "type/feature"
  color: "a2eeef"
  description: "New feature or request"
- name: "type/docs"
  color: "0075ca"
  description: "Documentation improvements"
- name: "type/chore"
  color: "e4e669"
  description: "Maintenance and housekeeping"
- name: "type/refactor"
  color: "d4c5f9"
  description: "Code restructuring, no behavior change"

# Status
- name: "status/blocked"
  color: "b60205"
  description: "Blocked by another issue or external factor"
- name: "status/in-progress"
  color: "0e8a16"
  description: "Being actively worked on"
- name: "status/needs-review"
  color: "fbca04"
  description: "Waiting for code review"

# Size (used by PR automation)
- name: "size/XS"
  color: "3CBF00"
  description: "< 10 lines changed"
- name: "size/S"
  color: "5D9801"
  description: "10–49 lines changed"
- name: "size/M"
  color: "7F7203"
  description: "50–199 lines changed"
- name: "size/L"
  color: "A14C05"
  description: "200–499 lines changed"
- name: "size/XL"
  color: "C32607"
  description: "500+ lines changed"

# Areas
- name: "area/ci"
  color: "006b75"
  description: "CI/CD and GitHub Actions"
- name: "area/components"
  color: "1d76db"
  description: "React components"
- name: "area/hooks"
  color: "5319e7"
  description: "Custom React hooks"
- name: "area/config"
  color: "c5def5"
  description: "Configuration files"

# Meta
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention needed"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or PR already exists"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "security"
  color: "e11d48"
  description: "Security-related issue"
- name: "stale"
  color: "ededed"
  description: "No recent activity"
- name: "major-update"
  color: "d93f0b"
  description: "Major version dependency update"
- name: "needs-review"
  color: "fbca04"
  description: "Waiting for review"
- name: "work-in-progress"
  color: "fef2c0"
  description: "Not ready for review"
- name: "pinned"
  color: "006b75"
  description: "Exempt from stale bot"
