# ============================================================================
# TEMPLATE: Python CI
# Copy to .github/workflows/ and customize for your project.
# ============================================================================
name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"   # ← your Python version
          cache: pip

      - name: Install linters
        run: pip install ruff mypy  # ← your linting tools

      - name: Ruff check
        run: ruff check .

      - name: Ruff format check
        run: ruff format --check .

      - name: Type check
        run: mypy src/              # ← your source directory

  test:
    name: Test (Python ${{ matrix.python }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: ["3.11", "3.12", "3.13"]  # ← versions to test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"   # ← or: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest --cov=src --cov-report=xml -v

      # Uncomment for coverage uploads:
      # - uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: coverage.xml

  build:
    name: Build package
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: pip install build twine

      - name: Build
        run: python -m build

      - name: Check package
        run: twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          retention-days: 7
