# ============================================================================
# TEMPLATE: Terraform Plan / Apply
# Copy to .github/workflows/ and customize for your project.
#
# Prerequisites:
#   - Terraform files in infrastructure/ directory (or update working-directory)
#   - Cloud credentials configured as secrets (AWS_ACCESS_KEY_ID, etc.)
#   - Optionally: Terraform Cloud token for remote state
# ============================================================================
name: Terraform

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/**"        # â† your Terraform directory
  pull_request:
    paths:
      - "infrastructure/**"

permissions:
  contents: read
  pull-requests: write

env:
  TF_VERSION: "1.9"               # â† Terraform version
  WORKING_DIR: infrastructure      # â† path to your .tf files
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # AWS_REGION: us-east-1

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          # For Terraform Cloud:
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform plan -input=false -no-color -out=tfplan 2>&1 | tee plan-output.txt
          echo "exitcode=$?" >> "$GITHUB_OUTPUT"

      - name: Comment plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('${{ env.WORKING_DIR }}/plan-output.txt', 'utf8');

            const marker = '<!-- terraform-plan -->';
            const body = [
              marker,
              '### ðŸ“‹ Terraform Plan',
              '',
              '<details>',
              '<summary>Show plan output</summary>',
              '',
              '```hcl',
              plan.slice(0, 60000),  // GitHub comment limit
              '```',
              '</details>',
            ].join('\n');

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const existing = comments.find(c => c.body.includes(marker));

            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.WORKING_DIR }}/tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    # Require manual approval via environment protection rules
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.WORKING_DIR }}

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -input=false -auto-approve tfplan
